"""Async report runner — executes a scheduled report and delivers it.

No Celery required. Called directly by APScheduler running inside the FastAPI process.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone

from bson import ObjectId
from croniter import croniter

from backend.core.database import get_db

logger = logging.getLogger(__name__)


async def run_schedule(schedule_id: str) -> dict:
    """Full pipeline: generate dashboard → deliver → record result."""
    db = get_db()

    schedule = await db.schedules.find_one({"_id": ObjectId(schedule_id)})
    if not schedule or not schedule.get("is_active"):
        return {"status": "skipped"}

    started_at = datetime.now(timezone.utc)

    run_doc = await db.schedule_runs.insert_one({
        "project_id": schedule["project_id"],
        "schedule_id": ObjectId(schedule_id),
        "schedule_name": schedule.get("name", ""),
        "started_at": started_at,
        "finished_at": None,
        "duration_ms": None,
        "status": "running",
        "error": None,
        "dashboard_id": None,
    })
    run_oid = run_doc.inserted_id

    try:
        dashboard_id = await _generate_report(schedule, db)
        await _deliver(schedule, dashboard_id, started_at, db)

        now = datetime.now(timezone.utc)
        duration_ms = int((now - started_at).total_seconds() * 1000)
        next_run = croniter(schedule["cron"], now).get_next(datetime)

        await db.schedules.update_one(
            {"_id": ObjectId(schedule_id)},
            {"$set": {
                "last_run_at": now,
                "last_run_status": "success",
                "last_run_error": None,
                "next_run_at": next_run,
                "last_dashboard_id": ObjectId(dashboard_id),
            }},
        )
        await db.schedule_runs.update_one(
            {"_id": run_oid},
            {"$set": {
                "finished_at": now,
                "duration_ms": duration_ms,
                "status": "success",
                "dashboard_id": ObjectId(dashboard_id),
            }},
        )
        logger.info("Schedule %s completed in %dms", schedule_id, duration_ms)
        return {"status": "success", "dashboard_id": dashboard_id}

    except Exception as exc:
        now = datetime.now(timezone.utc)
        duration_ms = int((now - started_at).total_seconds() * 1000)
        try:
            next_run = croniter(schedule["cron"], now).get_next(datetime)
        except Exception:
            next_run = None

        await db.schedules.update_one(
            {"_id": ObjectId(schedule_id)},
            {"$set": {
                "last_run_at": now,
                "last_run_status": "error",
                "last_run_error": str(exc)[:500],
                "next_run_at": next_run,
            }},
        )
        await db.schedule_runs.update_one(
            {"_id": run_oid},
            {"$set": {
                "finished_at": now,
                "duration_ms": duration_ms,
                "status": "error",
                "error": str(exc)[:500],
            }},
        )
        logger.error("Schedule %s failed: %s", schedule_id, exc)
        return {"status": "error", "error": str(exc)}


async def _generate_report(schedule: dict, db) -> str:
    """Return a new dashboard_id by snapshotting the scheduled dashboard."""
    if schedule.get("dashboard_id"):
        return await _snapshot_dashboard(str(schedule["dashboard_id"]), schedule, db)
    raise ValueError("Schedule must have a dashboard_id")


async def _snapshot_dashboard(source_id: str, schedule: dict, db) -> str:
    """Clone a dashboard by re-running its widget queries. Returns the new dashboard_id."""
    from backend.services.mindsdb_client import mindsdb

    source = await db.dashboards.find_one({"_id": ObjectId(source_id)})
    if not source:
        raise ValueError(f"Dashboard {source_id} not found")

    widgets = await db.widgets.find({"dashboard_id": ObjectId(source_id)}).to_list(100)
    now = datetime.now(timezone.utc)

    new_dash = await db.dashboards.insert_one({
        "project_id": source["project_id"],
        "name": f"{source['name']} — {now.strftime('%b %d, %Y')}",
        "description": f"Auto-generated by schedule: {schedule.get('name', '')}",
        "created_by": source.get("created_by"),
        "created_at": now,
        "updated_at": now,
        "is_public": False,
        "layout": source.get("layout", []),
        "settings": source.get("settings", {}),
    })
    new_id = str(new_dash.inserted_id)

    for w in widgets:
        new_w = {k: v for k, v in w.items() if k not in ("_id",)}
        new_w["dashboard_id"] = ObjectId(new_id)
        query = w.get("data_binding", {}).get("query", "")
        if query:
            try:
                result = await mindsdb.sql_query(query)
                # Normalize to the cached_data shape used across the app
                # (columns/rows), not MindsDB's raw column_names/data keys.
                new_w["cached_data"] = {
                    "columns": result.get("column_names", []),
                    "rows": result.get("data", []),
                    "fetched_at": datetime.now(timezone.utc),
                }
            except Exception as e:
                logger.warning("Widget query refresh failed: %s", e)
        await db.widgets.insert_one(new_w)

    return new_id


async def _deliver(schedule: dict, dashboard_id: str, started_at: datetime, db) -> None:
    """Send report via all configured delivery channels. Channel failures are logged, not raised."""
    from backend.services.delivery_service import delivery_service
    from backend.services.pdf_service import pdf_service

    channels = schedule.get("delivery", {}).get("channels", [])
    if not channels:
        return

    # Resolve org SMTP config (DB-stored wins over env vars)
    smtp_cfg = None
    try:
        project = await db.projects.find_one({"_id": schedule["project_id"]})
        if project:
            smtp_cfg = await delivery_service.get_org_smtp_config(db, str(project["org_id"]))
    except Exception:
        pass

    pdf_bytes = await pdf_service.generate_dashboard_pdf(dashboard_id, db)

    for ch in channels:
        ctype = ch.get("type")
        try:
            if ctype == "email" and ch.get("recipients"):
                await delivery_service.send_email(
                    to=ch["recipients"],
                    subject=f"Scheduled report: {schedule.get('name', '')}",
                    body=f"Report generated at {started_at.isoformat()}",
                    attachments=[{
                        "filename": f"{schedule.get('name', 'report')}.pdf",
                        "content": pdf_bytes,
                        "content_type": "application/pdf",
                    }],
                    smtp_cfg=smtp_cfg,
                )
            elif ctype == "telegram":
                tg_recipients = ch.get("recipients", [])
                if isinstance(tg_recipients, str):
                    tg_recipients = [r.strip() for r in tg_recipients.split(",") if r.strip()]
                for tg_id in tg_recipients:
                    await delivery_service.send_telegram_dashboard(tg_id, dashboard_id, db)
            elif ctype == "webhook" and ch.get("url"):
                await delivery_service.send_webhook(ch["url"], dashboard_id, db)
        except Exception as e:
            logger.warning("Delivery channel %s failed: %s", ctype, e)
